---

- hosts: webservers 
  become: true
  tasks:
  
  - name: Update Repository Index
    apt:
      update_cache: yes

  - name: Instal Apache2 Package
    apt:
      name: apache2

  - name: Add PHP support for Apache2
    apt:
      name: libapache2-mod-php


